-- Run this in the Supabase SQL Editor to create the tags table
-- and allow all authenticated users to manage tags.

-- 1. Create Tags Table (if not exists)
CREATE TABLE IF NOT EXISTS public.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(name, parent_id)
);

-- 2. Enable RLS
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

-- 3. Drop old restrictive policies
DROP POLICY IF EXISTS "Authenticated users can read tags" ON public.tags;
DROP POLICY IF EXISTS "Admins can manage tags" ON public.tags;
DROP POLICY IF EXISTS "Allow read access to all users" ON public.tags;
DROP POLICY IF EXISTS "Allow write access to all users" ON public.tags;

-- 4. Create permissive policies for all authenticated users
CREATE POLICY "Authenticated users can read tags" ON public.tags
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert tags" ON public.tags
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update tags" ON public.tags
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete tags" ON public.tags
    FOR DELETE USING (auth.role() = 'authenticated');

-- 5. Create object_tags table (linking tags to document nodes)
CREATE TABLE IF NOT EXISTS public.object_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT NOT NULL,
    tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(node_id, tag_id)
);

-- Enable RLS on object_tags
ALTER TABLE public.object_tags ENABLE ROW LEVEL SECURITY;

-- Policies for object_tags
DROP POLICY IF EXISTS "Authenticated users can read object_tags" ON public.object_tags;
CREATE POLICY "Authenticated users can read object_tags" ON public.object_tags
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can insert object_tags" ON public.object_tags;
CREATE POLICY "Authenticated users can insert object_tags" ON public.object_tags
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete object_tags" ON public.object_tags;
CREATE POLICY "Authenticated users can delete object_tags" ON public.object_tags
    FOR DELETE USING (auth.role() = 'authenticated');
