-- Migration to create or update generated_artifacts table
-- This table stores artifacts generated via NotebookLM MCP

CREATE TABLE IF NOT EXISTS public.generated_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    notebook_id TEXT NOT NULL,
    nlm_artifact_id TEXT,
    artifact_url TEXT,
    artifact_type TEXT NOT NULL,
    artifact_name TEXT NOT NULL,
    node_id BIGINT REFERENCES public.documents("nodeID") ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(nlm_artifact_id)
);

-- Add node_id column if it doesn't exist (for existing tables)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'generated_artifacts' 
        AND column_name = 'node_id'
    ) THEN
        ALTER TABLE public.generated_artifacts 
        ADD COLUMN node_id BIGINT REFERENCES public.documents("nodeID") ON DELETE SET NULL;
    END IF;
END $$;

-- Enable RLS on generated_artifacts
ALTER TABLE public.generated_artifacts ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read their own artifacts
CREATE POLICY IF NOT EXISTS "Users can read own artifacts" 
    ON public.generated_artifacts
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own artifacts
CREATE POLICY IF NOT EXISTS "Users can create artifacts" 
    ON public.generated_artifacts
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own artifacts
CREATE POLICY IF NOT EXISTS "Users can update own artifacts" 
    ON public.generated_artifacts
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own artifacts
CREATE POLICY IF NOT EXISTS "Users can delete own artifacts" 
    ON public.generated_artifacts
    FOR DELETE
    USING (auth.uid() = user_id);

-- Policy: Admins can see all artifacts
CREATE POLICY IF NOT EXISTS "Admins can read all artifacts"
    ON public.generated_artifacts
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.user_roles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_user_id ON public.generated_artifacts(user_id);
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_node_id ON public.generated_artifacts(node_id);
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_nlm_artifact_id ON public.generated_artifacts(nlm_artifact_id);
