// Script to create object_tags table
// Run with: node scripts/create_object_tags.js

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
    console.error('Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function createObjectTagsTable() {
    console.log('Creating object_tags table...');

    // Check if table exists first
    const { data: existingTable, error: checkError } = await supabase
        .from('object_tags')
        .select('id')
        .limit(1);

    if (!checkError) {
        console.log('object_tags table already exists!');
        return;
    }

    console.log('Table does not exist. Error:', checkError.message);
    console.log('\n=== Run this SQL in Supabase SQL Editor ===\n');
    console.log(`
-- Create object_tags table (linking tags to document nodes)
CREATE TABLE IF NOT EXISTS public.object_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT NOT NULL,
    tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(node_id, tag_id)
);

-- Enable RLS on object_tags
ALTER TABLE public.object_tags ENABLE ROW LEVEL SECURITY;

-- Policies for object_tags
DROP POLICY IF EXISTS "Authenticated users can read object_tags" ON public.object_tags;
CREATE POLICY "Authenticated users can read object_tags" ON public.object_tags
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can insert object_tags" ON public.object_tags;
CREATE POLICY "Authenticated users can insert object_tags" ON public.object_tags
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete object_tags" ON public.object_tags;
CREATE POLICY "Authenticated users can delete object_tags" ON public.object_tags
    FOR DELETE USING (auth.role() = 'authenticated');
    `);

    console.log('\n=== End of SQL ===\n');
    console.log('Go to: https://supabase.com/dashboard → Your Project → SQL Editor');
    console.log('Paste the SQL above and click "Run"');
}

createObjectTagsTable().catch(console.error);
