// Script to run SQL against Supabase
const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');

const supabaseUrl = process.env.VITE_SUPABASE_URL || 'https://fdwzsxntvxjlfcgllbuz.supabase.co';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseServiceKey) {
    console.error('Error: SUPABASE_SERVICE_ROLE_KEY environment variable is required.');
    console.log('You can find this in your Supabase Dashboard under Settings > API > service_role key');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

const sql = `
-- Create Tags Table (standalone)
CREATE TABLE IF NOT EXISTS public.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(name, parent_id)
);

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

-- Drop old policies first
DROP POLICY IF EXISTS "Authenticated users can read tags" ON public.tags;
DROP POLICY IF EXISTS "Authenticated users can insert tags" ON public.tags;
DROP POLICY IF EXISTS "Authenticated users can update tags" ON public.tags;
DROP POLICY IF EXISTS "Authenticated users can delete tags" ON public.tags;
DROP POLICY IF EXISTS "Admins can manage tags" ON public.tags;
DROP POLICY IF EXISTS "Allow read access to all users" ON public.tags;
DROP POLICY IF EXISTS "Allow write access to all users" ON public.tags;

-- Allow all authenticated users to manage tags
CREATE POLICY "Authenticated users can read tags" ON public.tags
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert tags" ON public.tags
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update tags" ON public.tags
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete tags" ON public.tags
    FOR DELETE USING (auth.role() = 'authenticated');
`;

async function run() {
    try {
        const { data, error } = await supabase.rpc('exec_sql', { sql_query: sql });
        if (error) {
            // RPC might not exist, try raw query
            console.log('RPC not available, trying direct...');
            // Direct SQL execution isn't available via supabase-js client
            // You need to use the dashboard or psql
            console.error('Cannot execute raw SQL via supabase-js client.');
            console.log('Please run the SQL manually in the Supabase Dashboard SQL Editor.');
            console.log('File: supabase/fix_tags_permissions.sql');
        } else {
            console.log('SQL executed successfully:', data);
        }
    } catch (err) {
        console.error('Error:', err.message);
    }
}

run();
