-- Initial Schema Migration to bootstrap documents table

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "public"."documents" (
    "nodeID" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "title" "text",
    "order" integer,
    "selected" boolean,
    "text" "text",
    "parentNodeID" bigint,
    "docid" bigint NOT NULL,
    "level" smallint,
    "type" "text" DEFAULT 'Node'::"text",
    "visible" boolean DEFAULT false,
    "children" boolean DEFAULT false,
    "url" "text" DEFAULT ''::"text",
    "urltype" "text",
    "user_id" "uuid",
    CONSTRAINT "documents_urltype_check" CHECK ((("urltype" = ANY (ARRAY['Url'::"text", 'Loop'::"text", 'Video'::"text", 'Audio'::"text", 'Image'::"text", 'Markdown'::"text", 'PDF'::"text", 'PNG'::"text"])) OR ("urltype" IS NULL)))
);

ALTER TABLE "public"."documents" OWNER TO "postgres";

ALTER TABLE "public"."documents" ALTER COLUMN "docid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."documents_docid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."documents" ALTER COLUMN "nodeID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."documents_nodeID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."documents"
    ADD CONSTRAINT "documents_pkey" PRIMARY KEY ("nodeID");
