-- Migration: Auth V1
-- Creates user_roles and document_permissions tables
-- Originally from supabase_migration_auth_v1.sql

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create a table to track user roles (Admin vs User)
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read roles (to check if they are admin)
DROP POLICY IF EXISTS "Read roles" ON public.user_roles;
CREATE POLICY "Read roles" ON public.user_roles FOR SELECT USING (true);

-- 2. Create document_permissions table
CREATE TABLE IF NOT EXISTS public.document_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT REFERENCES public.documents("nodeID") ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    access_level TEXT NOT NULL CHECK (access_level IN ('read_only', 'full_access')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(node_id, user_id)
);

-- Enable RLS on document_permissions
ALTER TABLE public.document_permissions ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see permissions assigned to them
DROP POLICY IF EXISTS "Read own permissions" ON public.document_permissions;
CREATE POLICY "Read own permissions" ON public.document_permissions 
    FOR SELECT USING (auth.uid() = user_id);

-- Helper function for Admin UI
CREATE OR REPLACE FUNCTION public.get_all_users()
RETURNS TABLE (id UUID, email TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Check if the calling user is an admin
    IF EXISTS (
        SELECT 1 FROM public.user_roles 
        WHERE user_id = auth.uid() AND role = 'admin'
    ) THEN
        RETURN QUERY SELECT u.id, u.email::text FROM auth.users u;
    ELSE
        RAISE EXCEPTION 'Access Denied: User is not an admin';
    END IF;
END;
$$;

-- 3. Modify Documents RLS to include permission-based access
-- Re-applying these here to ensure consistency, though they might be in other migrations too.

DROP POLICY IF EXISTS "Users can read own documents" ON public.documents;
DROP POLICY IF EXISTS "Users can read relevant documents" ON public.documents;
CREATE POLICY "Users can read relevant documents" ON public.documents
    FOR SELECT
    USING (
        auth.uid() = user_id 
        OR 
        EXISTS (
            SELECT 1 FROM public.document_permissions 
            WHERE node_id = public.documents."nodeID" 
            AND user_id = auth.uid()
        )
        OR
        EXISTS (
            SELECT 1 FROM public.user_roles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

DROP POLICY IF EXISTS "Users can update own documents" ON public.documents;
DROP POLICY IF EXISTS "Users can update relevant documents" ON public.documents;
CREATE POLICY "Users can update relevant documents" ON public.documents
    FOR UPDATE
    USING (
        auth.uid() = user_id 
        OR 
        EXISTS (
            SELECT 1 FROM public.document_permissions 
            WHERE node_id = public.documents."nodeID" 
            AND user_id = auth.uid() 
            AND access_level = 'full_access'
        )
        OR
        EXISTS (
            SELECT 1 FROM public.user_roles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    )
    WITH CHECK (
        auth.uid() = user_id 
        OR 
        EXISTS (
            SELECT 1 FROM public.document_permissions 
            WHERE node_id = public.documents."nodeID" 
            AND user_id = auth.uid() 
            AND access_level = 'full_access'
        )
         OR
        EXISTS (
            SELECT 1 FROM public.user_roles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- Insert the Admin User
DO $$
DECLARE
    admin_uid UUID;
BEGIN
    SELECT id INTO admin_uid FROM auth.users WHERE email = 'seanbaker513@gmail.com';
    
    IF admin_uid IS NOT NULL THEN
        -- Insert or Update role
        INSERT INTO public.user_roles (user_id, role)
        VALUES (admin_uid, 'admin')
        ON CONFLICT (user_id) DO UPDATE SET role = 'admin';
    END IF;
END $$;

-- Policies for document_permissions table management
-- Admins can Insert/Update/Delete permissions
DROP POLICY IF EXISTS "Admins manage permissions" ON public.document_permissions;
CREATE POLICY "Admins manage permissions" ON public.document_permissions
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.user_roles 
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );
