-- Migration: Bulk Uploads and Tagging Schema
-- Replaces previous version with correct schema from Plan

-- 1. Create Tags Table
CREATE TABLE IF NOT EXISTS public.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(name, parent_id)
);

-- Enable RLS on tags
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

-- Tags Policies
DROP POLICY IF EXISTS "Authenticated users can read tags" ON public.tags;
CREATE POLICY "Authenticated users can read tags" ON public.tags
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can manage tags" ON public.tags;
CREATE POLICY "Admins can manage tags" ON public.tags
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.user_roles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- 2. Create File Uploads Table
CREATE TABLE IF NOT EXISTS public.file_uploads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    file_path TEXT NOT NULL UNIQUE, -- Path in Supabase Storage
    original_name TEXT NOT NULL,
    file_size BIGINT,
    mime_type TEXT,
    uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on file_uploads
ALTER TABLE public.file_uploads ENABLE ROW LEVEL SECURITY;

-- File Uploads Policies
DROP POLICY IF EXISTS "Users can see own uploads" ON public.file_uploads;
CREATE POLICY "Users can see own uploads" ON public.file_uploads
    FOR SELECT USING (
        uploaded_by = auth.uid() 
        OR 
        EXISTS (
            SELECT 1 FROM public.user_roles 
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

DROP POLICY IF EXISTS "Authenticated users can insert uploads" ON public.file_uploads;
CREATE POLICY "Authenticated users can insert uploads" ON public.file_uploads
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can delete own uploads" ON public.file_uploads;
CREATE POLICY "Users can delete own uploads" ON public.file_uploads
    FOR DELETE USING (
        uploaded_by = auth.uid() 
        OR 
        EXISTS (
            SELECT 1 FROM public.user_roles 
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- 3. Create Object Tags Table (Mapping)
CREATE TABLE IF NOT EXISTS public.object_tags (
    file_id UUID REFERENCES public.file_uploads(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (file_id, tag_id)
);

-- Enable RLS on object_tags
ALTER TABLE public.object_tags ENABLE ROW LEVEL SECURITY;

-- Object Tags Policies
DROP POLICY IF EXISTS "Users can see tags for visible files" ON public.object_tags;
CREATE POLICY "Users can see tags for visible files" ON public.object_tags
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.file_uploads
            WHERE id = public.object_tags.file_id
            AND (
                uploaded_by = auth.uid()
                OR
                EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
            )
        )
    );

DROP POLICY IF EXISTS "Users can tag own files" ON public.object_tags;
CREATE POLICY "Users can tag own files" ON public.object_tags
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.file_uploads
            WHERE id = public.object_tags.file_id
            AND (
                uploaded_by = auth.uid()
                OR
                EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
            )
        )
    );

-- 4. Storage Bucket Setup
-- Note: Requires manual bucket creation if not exists, or via dashboard.
-- Attempting insert for local dev support
INSERT INTO storage.buckets (id, name, public)
VALUES ('uploads', 'uploads', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- Policy: Select (View) - Any authenticated user
CREATE POLICY "Authenticated users can select"
ON storage.objects FOR SELECT
USING ( bucket_id = 'uploads' AND auth.role() = 'authenticated' );

-- Policy: Insert (Upload) - Any authenticated user
CREATE POLICY "Authenticated users can upload"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'uploads' AND auth.role() = 'authenticated' );

-- Policy: Update - Owner
CREATE POLICY "Users can update own files"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'uploads' AND owner = auth.uid() );

-- Policy: Delete - Owner
CREATE POLICY "Users can delete own files"
ON storage.objects FOR DELETE
USING ( bucket_id = 'uploads' AND owner = auth.uid() );
