-- Migration: Refactor object_tags to associate with BlobStore files
-- This drops the existing node-based tagging and creates file-based tagging

-- 1. Drop existing object_tags table and policies
DROP POLICY IF EXISTS "Authenticated users can delete object_tags" ON public.object_tags;
DROP POLICY IF EXISTS "Authenticated users can insert object_tags" ON public.object_tags;
DROP POLICY IF EXISTS "Authenticated users can read object_tags" ON public.object_tags;
DROP TABLE IF EXISTS public.object_tags;

-- 2. Create new object_tags table with file_path
CREATE TABLE public.object_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path TEXT NOT NULL,
    tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(file_path, tag_id)
);

-- 3. Enable RLS
ALTER TABLE public.object_tags ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
CREATE POLICY "Authenticated users can read object_tags" ON public.object_tags
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert object_tags" ON public.object_tags
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete object_tags" ON public.object_tags
    FOR DELETE USING (auth.role() = 'authenticated');

-- 5. Add index for performance
CREATE INDEX idx_object_tags_file_path ON public.object_tags(file_path);
CREATE INDEX idx_object_tags_tag_id ON public.object_tags(tag_id);
