-- Migration: Create User Notebooks Table for NotebookLM
-- Stores cached notebook information per user for faster selection

-- 1. Create the notebooks table
CREATE TABLE IF NOT EXISTS public.user_notebooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    notebook_id TEXT NOT NULL,
    notebook_grp TEXT NOT NULL CHECK (notebook_grp IN (
        'Client', 
        'Tulkah AI', 
        'MDM', 
        'Process Mining', 
        'Antigravity', 
        'AI Developments', 
        'Other'
    )),
    notebook_nm TEXT NOT NULL,
    notebook_desc TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, notebook_id)
);

-- 2. Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_notebooks_user_id ON public.user_notebooks(user_id);
CREATE INDEX IF NOT EXISTS idx_user_notebooks_grp ON public.user_notebooks(notebook_grp);

-- 3. Enable RLS
ALTER TABLE public.user_notebooks ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Users can only see their own notebooks
DROP POLICY IF EXISTS "Users can read own notebooks" ON public.user_notebooks;
CREATE POLICY "Users can read own notebooks" ON public.user_notebooks
    FOR SELECT
    USING (auth.uid() = user_id);

-- Users can only insert/update/delete their own notebooks (though mostly done via RPC)
DROP POLICY IF EXISTS "Users can manage own notebooks" ON public.user_notebooks;
CREATE POLICY "Users can manage own notebooks" ON public.user_notebooks
    FOR ALL
    USING (auth.uid() = user_id);

-- 5. Create function to refresh notebooks
CREATE OR REPLACE FUNCTION public.sync_user_notebooks(
    notebooks_data JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user_id UUID;
BEGIN
    -- Get current user ID
    current_user_id := auth.uid();
    
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    -- Clear existing notebooks for this user
    DELETE FROM public.user_notebooks WHERE user_id = current_user_id;

    -- Insert new notebooks from JSONB array
    INSERT INTO public.user_notebooks (user_id, notebook_id, notebook_grp, notebook_nm, notebook_desc)
    SELECT 
        current_user_id,
        (notebook->>'notebook_id')::TEXT,
        (notebook->>'notebook_grp')::TEXT,
        (notebook->>'notebook_nm')::TEXT,
        (notebook->>'notebook_desc')::TEXT
    FROM jsonb_array_elements(notebooks_data) AS notebook;

END;
$$;

-- 6. Grant execute permissions
GRANT EXECUTE ON FUNCTION public.sync_user_notebooks(JSONB) TO authenticated;

-- 7. Add comments for documentation
COMMENT ON TABLE public.user_notebooks IS 'Cached NotebookLM notebooks per user';
COMMENT ON COLUMN public.user_notebooks.user_id IS 'Owner of the cached notebook list';
COMMENT ON COLUMN public.user_notebooks.notebook_id IS 'Unique identifier from NotebookLM';
COMMENT ON FUNCTION public.sync_user_notebooks(JSONB) IS 'Securely refreshes the cached notebooks list for the current user';
